LICENSE
README.md

Add an MIT license + a small readme.
close #6

add license and readme

---

commands/proposal_submission.go
commands/proposal_submission_test.go

Fix NewMarketSubmission with 0 value as decimal place

---

data-node/api/v1/trading_data.pb.gw.go
sources/data-node/grpc-rest-bindings.yml
swagger/data-node/api/v1/trading_data.swagger.json

Added REST endpoint for rewards information

---

commands/errors.go
commands/proposal_submission.go
commands/proposal_submission_test.go

close https://github.com/vegaprotocol/vega/issues/2548

add reference checks on proposal

---

commands/transaction.go

Add missing commands to the validations

add the delegations command to the commands checks

---

commands/transaction.go

Add support for restore command

---

.github/workflows/changelog-checker.yml
CHANGELOG.md

closes #161 
Also updated the changelog checker to run when needed

Update CHANGELOG.md for 0.46

---

CHANGELOG.md
commands/key_rotate_submission.go
commands/key_rotate_submission_test.go

Update validator function

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/spike_ticket.md
.github/ISSUE_TEMPLATE/technical_task.md
CHANGELOG.md
CODEOWNERS

closes #169 .
- Update templates
- Remove old GH action to add items to project board
- Tidy up changelog

Tidy up repo to align with team processes and workflows

---

CHANGELOG.md

Update `CHANGELOG.md` since GH Action implemented

---

CHANGELOG.md
sources/vega/commands/v1/transaction.proto
vega/commands/v1/transaction.pb.go

Closes #215 
This PR is for some suggestions that didn't make it into the first version of these descriptions.

Rewording of transaction nonce and block_height descriptions

---

sources/vega/chain_events.proto
vega/chain_events.pb.go

Update misleading comments on Index property for StakingEvent and ERC20Event

---

commands/transaction.go

add missing verification for lp commands

---

CHANGELOG.md
commands/proposal_submission.go
commands/proposal_submission_test.go

fix validation of risk params for log normal model

---

commands/proposal_submission.go
commands/proposal_submission_test.go

added missing check for sigma

---

CHANGELOG.md
Makefile

Closes #292 
Needs [this](https://github.com/vegaprotocol/devops-infra/pull/1185) change in devops-infra and re-deploying of the jenkins agent.

Re-enable proto check

---

CHANGELOG.md
sources/data-node/grpc-rest-bindings.yml

Add endpoint for partyless LP get

---

CHANGELOG.md
generated/json/data-node/api/v1/ObserveEventBusResponse.json
generated/proto.json
sources/vega/commands/v1/commands.proto
swagger/data-node/api/v1/trading_data.swagger.json
swagger/vega/api/v1/core.swagger.json
vega/commands/v1/commands.pb.go

Closes #366 
* replace market ID description under LP amend/cancel 
* remove redundant links 
* some grammar fixes

improve field descriptions for market ID

---

CHANGELOG.md
commands/liquidity_provision_submission.go
commands/liquidity_provision_submission_test.go
commands/order_amendment.go
commands/order_submission.go
commands/proposal_submission.go
commands/withdraw_submission.go

Actual fix here is on line 162.
close #369

fix: do not use price if integer is not valid

---

.github/ISSUE_TEMPLATE/bug_report.md

Updates the bug issue template to align with the new bug label format of:  `bug` with severities: `Low`, `Medium`, `Critical` and `Crasher`

chore: relabel the bug issue template

---

CHANGELOG.md
commands/order_submission_test.go
commands/proposal_submission.go
commands/proposal_submission_new_market_test.go

Prevent negative commitment amount in new market proposal

---

commands/proposal_submission.go
commands/proposal_submission_test.go

Make rationale optional in proposals for now.

fix: make rationale optional

---

generated/json/data-node/api/v1/ObserveEventBusResponse.json
generated/proto.json
swagger/data-node/api/v1/trading_data.swagger.json
swagger/vega/api/v1/core.swagger.json
swagger/vega/api/v1/corestate.swagger.json
vega/events/v1/events.pb.go

I accidently push the the change to the proto file straight to develop (apparently everyone in `Core` is an admin?): https://github.com/vegaprotocol/protos/commit/cf1b77cf23d1abd244aaac88e7a27f4f067dfa30
This PR follows up and also updates the generated files. It is just an update to a comment.

chore: also regenerate files
